# Generated by "buf config migrate-v1beta1". Edit as necessary, and
# remove this comment when you're finished.
#
# This module represents the "dir4/dir5/dir6" root found in
# the previous configuration file for the
# "buf.build/test/test" module.
version: v1
name: buf.build/test/test-dir4-dir5-dir6
deps:
  - buf.build/beta/googleapis
  - buf.build/beta/envoy
build:
  excludes:
    - dir7
breaking:
  use:
    - FILE
  ignore_only:
    FIELD_SAME_JSON_NAME:
      - file2.proto
lint:
  use:
    - DEFAULT
  ignore_only:
    ENUM_PASCAL_CASE:
      - file2.proto
