# Configuration file version.
version: "1.0"

# List of regexp patterns matching files the linter should include. When
# omitted/null, the linter includes all Go files. If assigned then only the
# files that their relative path (with respect to the config file path) matches
# any of the patterns will be processed.
#
# Note: The patterns must assume a Unix-like path (i.e., separated with forward
# slashes, `/`), even on Windows. This is to ensure a consistent behavior across
# different platforms.
#
# Example:
#   include:
#     - ^pkg/
#     - _foo.go$
include: null

# List of regexp patterns matching files the linter should skip. When
# omitted/null, the linter excludes no Go files. If assigned then only the
# files that their relative path (with respect to the config file path) does not
# match any of the patterns will be processed.
#
# Note: The patterns must assume a Unix-like path (i.e., separated with forward
# slashes, `/`), even on Windows. This is to ensure a consistent behavior across
# different platforms.
#
# Example:
#   exclude:
#     - ^internal/
#     - _autogenerated.go$
exclude:
  - ^private/gen

# Default set of rules to enable. Possible values are:
# - `basic`: enables basic rules which are: `pkg-doc`, `single-pkg-doc`, `start-with-name` and `deprecated`.
# - `all`:   all rules are enabled by default; the `disable` key can be used to disable specific rules.
# - `none`:  no rule is enabled by default; the `enable` key can be used to enable specific rules.
default: none

# List of rules to enable *in addition to* the default set.
#
# See the linter docs for more on supported rules.
#
# Example:
#   - pkg-doc
#   - single-pkg-doc
#   - require-pkg-doc
#   - specific-file-pkg-doc
#   - start-with-name
#   - require-doc
#   - deprecated
#   - max-len
#   - no-unused-link
enable:
  - pkg-doc
  - single-pkg-doc
  #- require-pkg-doc
  - specific-file-pkg-doc
  - start-with-name
  - require-doc
  - deprecated
  #- max-len
  - no-unused-link

# List of rules to disable.
#
# Example:
#   disable:
#     - pkg-doc
#     - single-pkg-doc
disable: null

# A map for setting individual rule options.
#
# All sub-keys are optional.
options:
  # Maximum line length for godocs, not including the `// `, or `/*` or `*/`
  # tokens.
  max-len/length: 120

  # Include test files when applying the `max-len` rule.
  max-len/include-tests: false

  # Include test files when applying the `pkg-doc` rule.
  pkg-doc/include-tests: false

  # Include test files when applying the `single-pkg-doc` rule.
  single-pkg-doc/include-tests: false

  # Include test files when applying the `require-pkg-doc` rule.
  require-pkg-doc/include-tests: false

  # Include test files when applying the `specific-file-pkg-doc` rule.
  specific-file-pkg-doc/include-tests: false

  # The file pattern to indicate which file should contain the package-level godoc when
  # applying the `specific-file-pkg-doc` rule.
  #
  # Valid values are:
  #
  #   - "doc": The godoc should be in a file named doc.go
  #   - "package-name": The godoc should be in a file named after the package. For example, if a package
  #     is named "foobar", the godoc should be in a file named "foobar.go".
  specific-file-pkg-doc/file-pattern: "package-name"

  # Include test files when applying the `require-doc` rule.
  require-doc/include-tests: false

  # Ignore exported (public) symbols when applying the `require-doc` rule.
  require-doc/ignore-exported: false

  # Ignore unexported (private) symbols when applying the `require-doc` rule.
  require-doc/ignore-unexported: true

  # Include test files when applying the `start-with-name` rule.
  start-with-name/include-tests: false

  # Include unexported (private) symbols when applying the `start-with-name` rule.
  start-with-name/include-unexported: false

  # Include test files when applying the `no-unused-link` rule.
  no-unused-link/include-tests: false
