run:
  skip-dirs-use-default: false
linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      # Use private/pkg/thread.Parallelize
      - '^errgroup\.'
      # Use private/pkg/command.Runner
      - '^exec\.Cmd$'
      - '^exec\.Command$'
      - '^exec\.CommandContext$'
      # os.Rename does not work across filesystem boundaries
      # See https://github.com/bufbuild/buf/issues/639
      - '^os\.Rename$'
      # Ban debug statements
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
  importas:
    alias:
      - pkg: github.com/bufbuild/buf/private/gen/proto/go/buf/alpha/image/v1
        alias: imagev1
      - pkg: github.com/bufbuild/buf/private/gen/proto/go/buf/alpha/module/v1
        alias: modulev1
      - pkg: github.com/bufbuild/buf/private/gen/proto/go/buf/alpha/registry/v1alpha1
        alias: registryv1alpha1
linters:
  enable:
    - govet
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - promlinter
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - wastedassign
    - whitespace
  disable-all: true
issues:
  exclude-rules:
    - linters:
        - forbidigo
      # this is the one file we want to allow exec.Cmd functions in
      path: private/pkg/command/runner.go
    - linters:
        - stylecheck
      text: "ST1005:"
    - linters:
        - errcheck
      # headers.go has casts with values from contexts that should fail if there
      # is no error, but it would be very unidiomatic to return an error from
      # the functions that do these casts, and we completely control the
      # context values within this file
      path: private/pkg/rpc/headers.go
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Password*
      # trip this off.
      path: private/buf/bufcli/bufcli.go
      text: "G101:"
    - linters:
        - gosec
      # G204 checks that exec.Command is not called with non-constants.
      # We call exec.Command for protoc and plugin proxying, and control the arguments completely.
      path: private/pkg/app/appproto/appprotoexec/binary_handler.go
      text: "G204:"
    - linters:
        - gosec
      # G204 checks that exec.Command is not called with non-constants.
      # We call exec.Command for protoc and plugin proxying, and control the arguments completely.
      path: private/pkg/app/appproto/appprotoexec/protoc_proxy_handler.go
      text: "G204:"
    - linters:
        - wastedassign
      # netrc/internal is a library largely copied in from an external repository with attribution.
      # We try to make minimal edits.
      path: private/pkg/netrc/internal/internal.go
      # we actually want to use this init in testing
    - linters:
        - gochecknoinits
      path: private/bufpkg/bufmodule/bufmoduletesting/bufmoduletesting.go
      # we actually want to use this init
    - linters:
        - gochecknoinits
      path: private/usage/usage.go
