version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - errcheck
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    forbidigo:
      forbid:
        - pattern: ^errgroup\.
        - pattern: ^exec\.Cmd$
        - pattern: ^exec\.Command$
        - pattern: ^exec\.CommandContext$
        - pattern: ^os\.Rename$
        - pattern: ^os\.Getwd$
        - pattern: ^os\.Chdir$
        - pattern: ^fmt\.Print
        - pattern: ^log\.
        - pattern: ^print$
        - pattern: ^println$
        - pattern: ^(proto|prototext|protojson|protoyaml).Marshal$
        - pattern: ^(proto|prototext|protojson|protoyaml).Unmarshal$
        - pattern: ^(proto|prototext|protojson|protoyaml).MarshalOptions$
        - pattern: ^(proto|prototext|protojson|protoyaml).UnmarshalOptions$
    govet:
      enable:
        - nilness
    importas:
      alias:
        - pkg: github.com/bufbuild/buf/private/gen/proto/go/buf/alpha/image/v1
          alias: imagev1
        - pkg: github.com/bufbuild/buf/private/gen/proto/go/buf/alpha/module/v1
          alias: modulev1
        - pkg: github.com/bufbuild/buf/private/gen/proto/go/buf/alpha/registry/v1alpha1
          alias: registryv1alpha1
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
        path-except: private/bufpkg/bufmodule/bufmoduleapi/convert.go
      - linters:
          - gosec
        path: private/buf/bufcli/env.go
        text: 'G101:'
      - linters:
          - gosec
        path: private/buf/buflsp/progress.go
        text: 'G404:'
      - linters:
          - gosec
        path: private/buf/buflsp/file.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/buf/buflsp/image.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/buf/buflsp/report.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/buf/buflsp/server.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/buf/buflsp/symbol.go
        text: 'G115:'
      - linters:
          - containedctx
        path: private/buf/bufcurl/reflection_resolver.go
      - linters:
          - gosec
        path: private/buf/bufcurl/tls.go
        text: 'G402:'
      - linters:
          - paralleltest
        path: private/buf/buffetch/internal/reader_test.go
        text: missing the call to method parallel
      - linters:
          - paralleltest
        path: private/buf/bufstudioagent/bufstudioagent_test.go
        text: missing the call to method parallel
      - linters:
          - paralleltest
        path: private/buf/cmd/buf/workspace_test.go
        text: missing the call to method parallel
      - linters:
          - forbidigo
        path: private/buf/cmd/buf/command/alpha/protoc/protoc_test.go
        text: os.Getwd
      - linters:
          - dogsled
        path: private/buf/cmd/buf/command/curl/curl.go
      - linters:
          - forbidigo
        path: private/buf/cmd/buf/command/generate/generate_test.go
        text: os.Getwd
      - linters:
          - gochecknoinits
        path: private/bufpkg/bufcas/proto.go
      - linters:
          - gochecknoinits
        path: private/bufpkg/bufconfig/module_config.go
      - linters:
          - gosec
        path: private/bufpkg/bufimage/bufimageutil/.*_test\.go
        text: 'G404:'
      - linters:
          - paralleltest
        path: private/bufpkg/bufimage/build_image_unix_test.go
        text: missing the call to method parallel
      - linters:
          - containedctx
        path: private/bufpkg/bufimage/parser_accessor_handler.go
      - linters:
          - containedctx
        path: private/bufpkg/bufmodule/module.go
      - linters:
          - containedctx
        path: private/bufpkg/bufmodule/module_set_builder.go
      - linters:
          - containedctx
        path: private/pkg/execext/process.go
      - linters:
          - gochecknoinits
        path: private/bufpkg/bufmodule/paths.go
      - linters:
          - forbidigo
        path: private/bufpkg/bufremoteplugin/bufremoteplugindocker/docker.go
        text: use of `errgroup
      - linters:
          - forbidigo
        path: private/pkg/execext/execext.go
      - linters:
          - forbidigo
        path: private/pkg/execext/process.go
      - linters:
          - gosec
        path: private/pkg/execext/execext.go
        text: 'G204:'
      - linters:
          - gosec
        path: private/pkg/git/git_test.go
        text: 'G504:'
      - linters:
          - wastedassign
        path: private/pkg/netrc/internal/internal.go
      - linters:
          - forbidigo
        path: private/pkg/osext/osext.go
        text: os.Getwd
      - linters:
          - forbidigo
        path: private/pkg/osext/osext.go
        text: os.Chdir
      - linters:
          - gochecknoinits
        path: private/pkg/protoencoding/detrand.go
      - linters:
          - errcheck
        path: private/pkg/rpc/headers.go
      - linters:
          - forbidigo
        path: private/pkg/storage/storageos/bucket.go
        text: os.Rename
      - linters:
          - containedctx
        path: private/pkg/transport/grpc/grpcclient/client_conn_provider.go
      - linters:
          - forbidigo
        path: private/pkg/transport/http/httpserver/httpserver.go
      - linters:
          - staticcheck
        text: 'ST1005:'
      - linters:
          - gochecknoinits
        path: private/usage/usage.go
      - linters:
          - staticcheck
        text: buf/alpha/registry/v1alpha1/plugin.proto is marked as deprecated
      - linters:
          - staticcheck
        text: buf/alpha/registry/v1alpha1/generate.proto is marked as deprecated
      - linters:
          - staticcheck
        text: GetDeprecatedLegacyJsonFieldConflicts is deprecated
      - linters:
          - forcetypeassert
        path: private/bufpkg/bufimage/source_retention_options_test\.go
      - linters:
          - paralleltest
        path: private/buf/cmd/buf/buf_test.go
        text: LsModules
      - linters:
          - gosec
        path: private/pkg/oauth2/device.go
        text: 'G101:'
      - linters:
          - gosec
        path: private/buf/bufgen/features.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/bufpkg/bufcheck/bufcheckserver/internal/buflintvalidate/field.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/bufpkg/bufremoteplugin/bufremoteplugin.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/buf/bufcurl/reflection_resolver.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/bufpkg/bufprotosource/paths.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/bufpkg/bufprotosource/option_extension_descriptor_test.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/buf/bufprotopluginexec/version.go
        text: 'G115:'
      - linters:
          - gosec
        path: private/bufpkg/bufcheck/bufcheckserver/internal/buflintvalidate/cel.go
        text: 'G115:'
      - linters:
          - staticcheck
        path: private/pkg/protoencoding/reparse_extensions_test.go
        text: 'SA1019:'
      - linters:
          - forbidigo
        path: private/pkg/protoencoding
        text: proto.Marshal
      - linters:
          - forbidigo
        path: private/pkg/protoencoding
        text: proto.Unmarshal
      - linters:
          - forbidigo
        path: private/pkg/protoencoding
        text: protojson.Marshal
      - linters:
          - forbidigo
        path: private/pkg/protoencoding
        text: protojson.Unmarshal
      - linters:
          - forbidigo
        path: private/pkg/protoencoding
        text: protoyaml.Marshal
      - linters:
          - forbidigo
        path: private/pkg/protoencoding
        text: protoyaml.Unmarshal
      - linters:
          - forbidigo
        path: private/pkg/protoencoding
        text: prototext.Marshal
      - linters:
          - forbidigo
        path: private/pkg/protoencoding
        text: prototext.Unmarshal
      - linters:
          - gosec
        path: private/bufpkg/bufcheck/bufcheckserver/internal/buflintvalidate/predefined_rules.go
        text: 'G115:'
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
