# Copyright 2020 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  skip-dirs-use-default: false
linters-settings:
  errcheck:
    check-type-assertions: true
linters:
  enable:
    - govet
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - gochecknoinits
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
  disable-all: true
issues:
  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1005:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Password*
      # trip this off.
      path: internal/buf/bufcli/bufcli.go
      text: "G101:"
    - linters:
        - gosec
      # G204 checks that exec.Command is not called with non-constants.
      # We call exec.Command for protoc and plugin proxying, and control the arguments completely.
      path: internal/pkg/app/appproto/appprotoexec/binary_handler.go
      text: "G204:"
    - linters:
        - gosec
      # G204 checks that exec.Command is not called with non-constants.
      # We call exec.Command for protoc and plugin proxying, and control the arguments completely.
      path: internal/pkg/app/appproto/appprotoexec/protoc_proxy_handler.go
      text: "G204:"
      # we actually want to use this init in testing
    - linters:
        - gochecknoinits
      path: internal/buf/bufcore/bufmodule/bufmoduletesting/bufmoduletesting.go
