- id: buf-generate
  name: buf generate
  language: golang
  language_version: 1.25.6
  entry: buf generate
  types: [proto]
  pass_filenames: false
- id: buf-build
  name: buf build
  language: golang
  language_version: 1.25.6
  entry: buf build
  types: [proto]
  pass_filenames: false
- id: buf-breaking
  name: buf breaking
  language: golang
  language_version: 1.25.6
  entry: buf breaking
  types: [proto]
  pass_filenames: false
- id: buf-lint
  name: buf lint
  language: golang
  language_version: 1.25.6
  entry: buf lint
  types: [proto]
  pass_filenames: false
- id: buf-format
  name: buf format
  language: golang
  language_version: 1.25.6
  entry: buf format -w --exit-code
  types: [proto]
  pass_filenames: false
- id: buf-dep-update
  name: buf dep update
  language: golang
  language_version: 1.25.6
  entry: buf dep update
  files: '(buf\.lock|buf\.yaml)'
  pass_filenames: false
- id: buf-dep-prune
  name: buf dep prune
  language: golang
  language_version: 1.25.6
  entry: buf dep prune
  files: '(buf\.lock|buf\.yaml)'
  pass_filenames: false
  # Deprecated: use buf-dep-update instead.
- id: buf-mod-update
  name: buf mod update
  language: golang
  language_version: 1.25.6
  entry: buf mod update
  files: '(buf\.lock|buf\.yaml)'
  pass_filenames: false
  # Deprecated: use buf-dep-prune instead.
- id: buf-mod-prune
  name: buf mod prune
  language: golang
  language_version: 1.25.6
  entry: buf mod prune
  files: '(buf\.lock|buf\.yaml)'
  pass_filenames: false
