- id: buf-generate
  name: buf generate
  language: golang
  entry: buf generate
  types: [proto]
  pass_filenames: false
- id: buf-breaking
  name: buf breaking
  language: golang
  entry: buf breaking
  types: [proto]
  pass_filenames: false
- id: buf-lint
  name: buf lint
  language: golang
  entry: buf lint
  types: [proto]
  pass_filenames: false
- id: buf-format
  name: buf format
  language: golang
  entry: buf format -w --exit-code
  types: [proto]
  pass_filenames: false
- id: buf-mod-update
  name: buf mod update
  language: golang
  entry: buf mod update
  files: '(buf\.lock|buf\.yaml)'
  pass_filenames: false
- id: buf-mod-prune
  name: buf mod prune
  language: golang
  entry: buf mod prune
  files: '(buf\.lock|buf\.yaml)'
  pass_filenames: false
