- id: buf-breaking
  name: buf breaking
  language: golang
  entry: buf breaking
  # match files ending in .proto,
  files: &protofiles '[^/]+\.proto$'
  pass_filenames: false
- id: buf-lint
  name: buf lint
  language: golang
  entry: buf lint
  files: *protofiles
  pass_filenames: false
- id: buf-format
  name: buf format
  language: golang
  entry: buf format -w --exit-code
  files: *protofiles
  pass_filenames: false
