- id: buf-breaking
  name: buf breaking
  language: golang
  entry: buf breaking
  types: [proto]
  pass_filenames: false
- id: buf-lint
  name: buf lint
  language: golang
  entry: buf lint
  types: [proto]
  pass_filenames: false
- id: buf-format
  name: buf format
  language: golang
  entry: buf format -w --exit-code
  types: [proto]
  pass_filenames: false
