ARG DOCKER_WORKSPACE_IMAGE

FROM $DOCKER_WORKSPACE_IMAGE as builder

COPY cmd ./cmd
COPY internal ./internal
RUN go build -o /go/bin/buf ./cmd/buf

FROM alpine:3.10

RUN apk add --update --no-cache \
    ca-certificates && \
  rm -rf /var/cache/apk/*

COPY --from=builder /go/bin/buf /usr/local/bin/buf

ENTRYPOINT ["/usr/local/bin/buf"]
