ARG DOCKER_WORKSPACE_IMAGE

FROM $DOCKER_WORKSPACE_IMAGE as builder

COPY cmd ./cmd
COPY internal ./internal
RUN go build -ldflags "-s -w" -trimpath -o /go/bin/buf ./cmd/buf

FROM alpine:3.12.0

RUN apk add --update --no-cache \
    ca-certificates \
    git \
    openssh-client && \
  rm -rf /var/cache/apk/*

COPY --from=builder /go/bin/buf /usr/local/bin/buf

ENTRYPOINT ["/usr/local/bin/buf"]
