# Generated by "buf config migrate-v1beta1". Edit as necessary, and
# remove this comment when you're finished.
#
# This module represents the "dir2/dir4" root found in
# the previous configuration file for the
# "buf.build/test/test" module.
version: v1
name: buf.build/test/test-dir2-dir4
deps:
  - buf.build/beta/googleapis
  - buf.build/beta/envoy
build:
  excludes:
    - dir5
breaking:
  use:
    - FILE
  ignore:
    - file.proto
lint:
  use:
    - DEFAULT
  ignore:
    - file.proto
