name: Bug Report
description: File a bug report.
labels: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve Buf by filing bugs, we really appreciate it! For us to investigate your issue efficiently, we need a minimal reproducible example. We get lots of support requests, so please help us help you. We find that the easiest way to do this is by linking to a GitHub repository with the setup of the example, as well as a set of commands for us to run on this GitHub repository to reproduce the issue. You can use an existing GitHub repository, or a temporary GitHub repository you create.

        **If you do not provide a minimal reproducible example in a GitHub repository, we may have to close your issue. We apologize, but we have to be efficient with our support requests, and we appreciate your help.**

        [This article](https://stackoverflow.com/help/minimal-reproducible-example) on minimal reproducible examples may be of use!
  - type: input
    id: github-repository
    attributes:
      label: GitHub repository with your minimal reproducible example (do not fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)
      description: Provide us with a link to the GitHub repository that contains the setup needed to reproduce the issue. This is a repository you create, and is required for us to investigate your issue.
      placeholder: https://github.com/you/temp-repo-with-repro
    validations:
      required: true
  - type: textarea
    id: commands
    attributes:
      label: Commands
      description: Please provide the commands to run from the root of this repository to reproduce the issue.
      placeholder: |
        cd ./proto
        buf lint
      render: shell
    validations:
      required: true
  - type: textarea
    id: actual-output
    attributes:
      label: Output
      description: What is the output of running these commands?
      placeholder: |
        foo/bar/v1/bar.proto:37:29:Field name "CreateTime" should be lower_snake_case, such as "create_time".
      render: shell
    validations:
      required: true
  - type: textarea
    id: expected-output
    attributes:
      label: Expected Output
      description: What did you expect instead?
      placeholder: I expected no lint failures.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Is there any other context you'd like us to have?
