name: Create a PR
description: This action creates a new branch, commits current changes and creates a PR.
inputs:
  branch:
    description: The branch to create and open a PR for.
    required: true
  commit_message:
    description: The commit message.
    required: true
  title:
    description: The PR's title.
    required: true
  body:
    description: The PR's body.
    required: true
  token:
    description: The GitHub token.
    required: true
outputs:
  pr_url:
    description: The URL of the pull request
    value: ${{ steps.create_pr.outputs.url }}
runs:
  using: "composite"
  steps:
    - run: git config --global user.name "${{ github.actor }}"
      shell: bash
    - run: git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      shell: bash
    - run: git checkout -b "${{ inputs.branch }}"
      shell: bash
    - run: git add .
      shell: bash
    - run: git commit -m "${{ inputs.commit_message }}"
      shell: bash
    - run: git push origin "${{ inputs.branch }}" --force
      shell: bash
    - run: echo "url=$(gh pr create --title "${{ inputs.title }}" --body "${{ inputs.body }}")" >> $GITHUB_OUTPUT
      id: create_pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      # todo: remove
    - run: echo "pr url is ${{ steps.create_pr.outputs.url }}"
      shell: bash
