# Generated by "buf config migrate-v1beta1". Edit as necessary, and
# remove this comment when you're finished.
#
# This module represents the "." root found in
# the previous configuration file for the
# "buf.build/test/test" module.
version: v1
name: buf.build/test/test
deps:
  - buf.build/beta/googleapis
  - buf.build/beta/envoy
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
