# Generated by "buf config migrate-v1beta1". Edit as necessary, and
# remove this comment when you're finished.
#
# This module represents the "." root found in
# the previous configuration.
version: v1
deps:
  - buf.build/beta/googleapis
