name: binary-size
on: push
# Prevent writing to the repository using the CI token.
# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions: read-all
env:
  MAKEFLAGS: "-j 2"
jobs:
  buf-binary-size:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/buf/${{ runner.os }}/x86_64/bin
            ~/.cache/buf/${{ runner.os }}/x86_64/go/pkg/mod
            ~/.cache/buf/${{ runner.os }}/x86_64/gocache
            ~/.cache/buf/${{ runner.os }}/x86_64/include
            ~/.cache/buf/${{ runner.os }}/x86_64/versions
          key: ${{ runner.os }}-buf-${{ hashFiles('**/go.sum', 'make/**') }}
          restore-keys: |
            ${{ runner.os }}-buf-
      - name: make-bufbinarysize
        run: make bufbinarysize
