name: Buf CI
on:
  push:
    paths:
      - 'proto/**'
      - '.github/workflows/buf-ci.yaml'
  pull_request:
    paths:
      - 'proto/**'
      - '.github/workflows/buf-ci.yaml'
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v0.1
        with:
          token: ${{ secrets.BUF_TOKEN }}
