on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      commit_message:
        required: true
        type: string
      title:
        required: true
        type: string
      body:
        required: true
        type: string
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps: 
    - name: Set up username
      run: git config --global user.name "${{ github.actor }}"
    - name: Set up email
      run: git config --global user.email "${{ github.actor }}@users.noreply.github.com"
    - name: Check out branch
      run: git checkout -b "${{ inputs.branch }}"
    - name: Add changes
      run: git add .
    - name: Commit changes
      run: git commit -m "${{ inputs.commit_message }}"
    - name: Push branch
      run: git push origin "${ inputs.branch }" --force
    - name: Create PR
      run: gh pr create --title "${{ inputs.title }}" --body "${{ inputs.body }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
