name: Create Release PR
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version you intend to release without leading 'v' (eg x.y.z and not vx.y.z)

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Validate input version does not start with 'v'
        if: ${{ env.VERSION == '' || startsWith(env.VERSION, 'v') }}
        run: |
          echo "version '${{ env.VERSION}}' is invalid, it must not be empty or start with 'v'"
          exit 1
      # - name: Validate input version
        # run: if [[ '${{ env.VERSION }}' == v* ]];then echo 'version must not start with v';exit 1;fi
      - name: Checkout repository code
        uses: actions/checkout@v4
      # temporarily skipped
      # - name: setup-go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: "1.21.x"
      # - name: Install Buf
      #   run: make installbuf
      - name: Update Buf Version
        run: make updateversion
      - name: Update Changelog Version
        run: make releasechangelog
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          add-paths: .
          commit-message: "Update version to v${{env.VERSION}}"
          branch: release/v${{env.VERSION}}
          title: "Release v${{env.VERSION}}"
          delete-branch: true
          body: |
            Release prepared for ${{env.VERSION}}

            Reminder: Update the changelog
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release PR
        run: |
          PR_BRANCH=release/v${{ env.VERSION }}
          git checkout -b "${PR_BRANCH}"
          git add .
          git commit -m "Update version to v${{ env.VERSION }}"
          git push origin "${PR_BRANCH}" --force
          gh pr create --title "Release v${{env.VERSION}}" --template a.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # placeholder for slack notification