name: Make upgrade
on:
  schedule:
    # Run every Monday at 10am UTC
    - cron: "0 10 * * 1"
env:
  APP_ID: 251311
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app_token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ secrets.TOKEN_EXCHANGE_GH_APP_PRIVATE_KEY }}
      - name: Checkout repository code
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app_token.outputs.token }}
      - name: setup-go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.x"
          check-latest: true
          cache: false
      - name: Set up Git name and email
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: make-githubactionupgrade
        run: make githubactionupgrade
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
