name: PR Approval Bypass Notifier
on:
  pull_request:
    types:
      - closed
    branches:
      - main
permissions:
  pull-requests: read
jobs:
  approval:
    uses: bufbuild/base-workflows/.github/workflows/notify-approval-bypass.yaml@main
    secrets: inherit
