name: npm-publish
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version you intend to publish (eg x.y.z)
  release:
    types: [ created ]

jobs:
  publish:
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
      - name: npm-auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc
      - name: publish
        run: make npmpublish
        env:
          VERSION: ${{ github.event.inputs.version || github.event.release.name }}