# NOTE: This filename is hardcoded in our trusted publishing setup on npmjs.com;
# do not change this filename without updating it there as well.
name: Publish to npm
on:
  # Triggers on pull requests to verify packaging-related changes with smoke tests.
  # Below, we filter to make sure not to run on the release PR itself where it
  # would fail since the release binaries aren't ready yet.
  pull_request:
    paths:
      - 'packaging/npm/**'
      - '.github/workflows/publish-npm.yaml'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || !startsWith(github.event.pull_request.head.ref, 'release')
    permissions:
      contents: read
    defaults:
      run:
        working-directory: packaging/npm
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - run: bash scripts/generate_packages.bash

      - uses: actions/upload-artifact@v7
        with:
          name: npm-packages
          path: packaging/npm/dist/

  smoke-test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-15-intel
          - windows-latest
          - windows-11-arm
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: packaging/npm
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - uses: actions/download-artifact@v8
        with:
          name: npm-packages
          path: packaging/npm/dist/

      - run: bash scripts/smoke_test.bash

  publish:
    if: github.event_name == 'release'
    needs: smoke-test
    runs-on: ubuntu-latest
    environment: npm-release
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: packaging/npm
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v8
        with:
          name: npm-packages
          path: packaging/npm/dist/

      - uses: actions/setup-node@v7
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 24

      - run: bash scripts/publish.bash
